package com.user.services.domain.objects;

import java.io.Serializable;
import java.util.Collection;
import java.util.List;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Entity
@Getter @Setter @NoArgsConstructor
public class User implements Serializable{

	/**
	 * Generated by STS
	 */
	private static final long serialVersionUID = 1462784503274272816L;
	
	@Id
	@GeneratedValue
	private int userId;
	private String firstName;
	private String lastName;
	private String userServiceType;
	
	@Override
	public String toString() {
		return "User [user_id=" + userId + ", firstName=" + firstName + ", lastName=" + lastName + ", userServiceType="
				+ userServiceType + "]";
	}
	

}

